In [4]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

In [5]:
df = pd.read_csv('data/water_potability.csv')
df

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,NaN,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135,0
1,3.716080,129.422921,18630.057858,6.635246,NaN,592.885359,15.180013,56.329076,4.500656,0
2,8.099124,224.236259,19909.541732,9.275884,NaN,418.606213,16.868637,66.420093,3.055934,0
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771,0
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,0
...,...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,47580.991603,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821,1
3272,7.808856,193.553212,17329.802160,8.061362,NaN,392.449580,19.903225,NaN,2.798243,1
3273,9.419510,175.762646,33155.578218,7.350233,NaN,432.044783,11.039070,69.845400,3.298875,1
3274,5.126763,230.603758,11983.869376,6.303357,NaN,402.883113,11.168946,77.488213,4.708658,1
3275,7.874671,195.102299,17404.177061,7.509306,NaN,327.459760,16.140368,78.698446,2.309149,1

In [6]:
X = df.drop("Potability", axis=1)
y = df["Potability"]

In [7]:
X = X.fillna(X.median())
X

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity
0,7.036752,204.890455,20791.318981,7.300212,368.516441,564.308654,10.379783,86.990970,2.963135
1,3.716080,129.422921,18630.057858,6.635246,333.073546,592.885359,15.180013,56.329076,4.500656
2,8.099124,224.236259,19909.541732,9.275884,333.073546,418.606213,16.868637,66.420093,3.055934
3,8.316766,214.373394,22018.417441,8.059332,356.886136,363.266516,18.436524,100.341674,4.628771
4,9.092223,181.101509,17978.986339,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075
...,...,...,...,...,...,...,...,...,...
3271,4.668102,193.681735,47580.991603,7.166639,359.948574,526.424171,13.894419,66.687695,4.435821
3272,7.808856,193.553212,17329.802160,8.061362,333.073546,392.449580,19.903225,66.622485,2.798243
3273,9.419510,175.762646,33155.578218,7.350233,333.073546,432.044783,11.039070,69.845400,3.298875
3274,5.126763,230.603758,11983.869376,6.303357,333.073546,402.883113,11.168946,77.488213,4.708658
3275,7.874671,195.102299,17404.177061,7.509306,333.073546,327.459760,16.140368,78.698446,2.309149

In [9]:
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[0.50262515, 0.57113901, 0.33609646, ..., 0.31340165, 0.69975313,
        0.28609102],
       [0.26543429, 0.29740043, 0.30061142, ..., 0.49731851, 0.4509993 ,
        0.57679264],
       [0.57850887, 0.64131081, 0.32161885, ..., 0.56201674, 0.5328657 ,
        0.30363656],
       ...,
       [0.67282217, 0.46548556, 0.53910122, ..., 0.33866167, 0.56065454,
        0.34956996],
       [0.36619735, 0.66440723, 0.19148981, ..., 0.34363779, 0.62265916,
        0.61611996],
       [0.56247653, 0.53563505, 0.28048408, ..., 0.5341137 , 0.63247754,
        0.16244074]])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42, stratify=y)

In [11]:
from sklearn.metrics import accuracy_score

k_values = range(1, 30)
accuracy_list = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    preds = knn.predict(X_test)
    acc = accuracy_score(y_test, preds)
    accuracy_list.append(acc)
    print(f"K = {k} --> Accuracy = {acc}")

best_k = k_values[np.argmax(accuracy_list)]
best_acc = max(accuracy_list)

print("\n==============================")
print("Best K:", best_k)
print("Best Accuracy:", best_acc)
print("==============================")

# train final KNN model with best K
best_knn = KNeighborsClassifier(n_neighbors=best_k)
best_knn.fit(X_train, y_train)
final_preds = best_knn.predict(X_test)

print("\nConfusion Matrix for Best KNN:")
print(confusion_matrix(y_test, final_preds))

K = 1 --> Accuracy = 0.5701219512195121
K = 2 --> Accuracy = 0.6082317073170732
K = 3 --> Accuracy = 0.5975609756097561
K = 4 --> Accuracy = 0.614329268292683
K = 5 --> Accuracy = 0.6082317073170732
K = 6 --> Accuracy = 0.6128048780487805
K = 7 --> Accuracy = 0.6036585365853658
K = 8 --> Accuracy = 0.6082317073170732
K = 9 --> Accuracy = 0.6128048780487805
K = 10 --> Accuracy = 0.6189024390243902
K = 11 --> Accuracy = 0.6189024390243902
K = 12 --> Accuracy = 0.6280487804878049
K = 13 --> Accuracy = 0.6219512195121951
K = 14 --> Accuracy = 0.6234756097560976
K = 15 --> Accuracy = 0.6204268292682927
K = 16 --> Accuracy = 0.6189024390243902
K = 17 --> Accuracy = 0.6280487804878049
K = 18 --> Accuracy = 0.625
K = 19 --> Accuracy = 0.6265243902439024
K = 20 --> Accuracy = 0.6189024390243902
K = 21 --> Accuracy = 0.614329268292683
K = 22 --> Accuracy = 0.625
K = 23 --> Accuracy = 0.6295731707317073
K = 24 --> Accuracy = 0.6204268292682927
K = 25 --> Accuracy = 0.6173780487804879
K = 26 --> Accuracy = 0.6189024390243902
K = 27 --> Accuracy = 0.6189024390243902
K = 28 --> Accuracy = 0.614329268292683
K = 29 --> Accuracy = 0.6158536585365854

==============================
Best K: 23
Best Accuracy: 0.6295731707317073
==============================

Confusion Matrix for Best KNN:
[[366  34]
 [209  47]]

In [12]:
kernels = ["linear", "rbf", "poly", "sigmoid"]

print("SVM RESULTS\n")

for k in kernels:
    model = SVC(kernel=k)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)

    acc = accuracy_score(y_test, preds)
    cm = confusion_matrix(y_test, preds)

    print(f"\nKernel: {k.upper()}")
    print("Accuracy:", acc)
    print("Confusion Matrix:\n", cm)

SVM RESULTS


Kernel: LINEAR
Accuracy: 0.6097560975609756
Confusion Matrix:
 [[400   0]
 [256   0]]

Kernel: RBF
Accuracy: 0.6600609756097561
Confusion Matrix:
 [[375  25]
 [198  58]]

Kernel: POLY
Accuracy: 0.663109756097561
Confusion Matrix:
 [[363  37]
 [184  72]]

Kernel: SIGMOID
Accuracy: 0.6097560975609756
Confusion Matrix:
 [[400   0]
 [256   0]]

In [13]:
from sklearn.metrics import classification_report

rbf_model = SVC(kernel='rbf')
rbf_model.fit(X_train, y_train)

# Predictions
y_pred_rbf = rbf_model.predict(X_test)
# Classification Report
print("Classification Report (RBF SVM):")
print(classification_report(y_test, y_pred_rbf))

Classification Report (RBF SVM):
              precision    recall  f1-score   support

           0       0.65      0.94      0.77       400
           1       0.70      0.23      0.34       256

    accuracy                           0.66       656
   macro avg       0.68      0.58      0.56       656
weighted avg       0.67      0.66      0.60       656